/*

    GLAD - OpenGL loader generated by dav1d炼

    Language/Generator: C/C++
    Specification: gl
    APIs: gl=3.3
    Profile: core
    Extensions:

    Do not consider this a valid header file for any purpose.
    This is a minimal stub for compilation purposes only.

*/
#ifndef __glad_h_
#define __glad_h_

#ifdef __gl3_h_
#  error OpenGL 3.3 header already included (API: gles3), remove previous include!
#endif
#define __gl3_h_

#define GL_VERSION_1_0 1
#define GL_VERSION_1_1 1
#define GL_VERSION_1_2 1
#define GL_VERSION_1_3 1
#define GL_VERSION_1_4 1
#define GL_VERSION_1_5 1
#define GL_VERSION_2_0 1
#define GL_VERSION_2_1 1
#define GL_VERSION_3_0 1
#define GL_VERSION_3_1 1
#define GL_VERSION_3_2 1
#define GL_VERSION_3_3 1

#include <stddef.h>
#include <stdlib.h>
#include <string.h>
#include <GL/gl.h>

typedef void* (*GLADloadproc)(const char *name);

int gladLoadGLLoader(GLADloadproc);

#define GL_DEPTH_BUFFER_BIT 0x00000100
#define GL_STENCIL_BUFFER_BIT 0x00000400
#define GL_COLOR_BUFFER_BIT 0x00004000
#define GL_FALSE 0
#define GL_TRUE 1
#define GL_TRIANGLES 0x0004
#define GL_TRIANGLE_FAN 0x0006
#define GL_BYTE 0x1400
#define GL_UNSIGNED_BYTE 0x1401
#define GL_SHORT 0x1402
#define GL_UNSIGNED_SHORT 0x1403
#define GL_INT 0x1404
#define GL_UNSIGNED_INT 0x1405
#define GL_FLOAT 0x1406
#define GL_FIXED 0x140C
#define GL_VERTEX_SHADER 0x8B31
#define GL_FRAGMENT_SHADER 0x8B30
#define GL_ARRAY_BUFFER 0x8892
#define GL_STATIC_DRAW 0x88E4
#define GL_DYNAMIC_DRAW 0x88E8
#define GL_TEXTURE0 0x84C0
#define GL_TEXTURE_2D 0x0DE1
#define GL_TEXTURE_MIN_FILTER 0x2801
#define GL_TEXTURE_MAG_FILTER 0x2800
#define GL_TEXTURE_WRAP_S 0x2802
#define GL_TEXTURE_WRAP_T 0x2803
#define GL_CLAMP_TO_EDGE 0x812F
#define GL_LINEAR 0x2601
#define GL_RGBA 0x1908
#define GL_RGBA32F 0x8814
#define GL_UNIFORM_BUFFER 0x8A11

typedef void (APIENTRYP PFNGLCLEARPROC) (GLbitfield mask);
typedef void (APIENTRYP PFNGLCLEARCOLORPROC) (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
typedef void (APIENTRYP PFNGLENABLEVERTEXATTRIBARRAYPROC) (GLuint index);
typedef void (APIENTRYP PFNGLDISABLEVERTEXATTRIBARRAYPROC) (GLuint index);
typedef void (APIENTRYP PFNGLBINDTEXTUREPROC) (GLenum target, GLuint texture);
typedef void (APIENTRYP PFNGLACTIVETEXTUREPROC) (GLenum texture);
typedef void (APIENTRYP PFNGLBINDVERTEXARRAYPROC) (GLuint array);
typedef void (APIENTRYP PFNGLBINDBUFFERPROC) (GLenum target, GLuint buffer);
typedef void (APIENTRYP PFNGLBUFFERSUBDATAPROC) (GLenum target, GLintptr offset, GLsizeiptr size, const void *data);
typedef void (APIENTRYP PFNGLDRAWRANGEELEMENTSPROC) (GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const void *indices);
typedef void (APIENTRYP PFNGLDRAWARRAYSPROC) (GLenum mode, GLint first, GLsizei count);
typedef GLenum (APIENTRYP PFNGLGETERRORPROC) (void);
typedef void (APIENTRYP PFNGLGETINTEGERVPROC) (GLenum pname, GLint *data);
typedef void (APIENTRYP PFNGGETSTRINGPROC) (GLenum name);
typedef void (APIENTRYP PFNGUNIFORM1IPROC) (GLint location, GLint v0);
typedef void (APIENTRYP PFNGUNIFORM1FPROC) (GLint location, GLfloat v0);
typedef void (APIENTRYP PFNGUNIFORM2FPROC) (GLint location, GLfloat v0, GLfloat v1);
typedef void (APIENTRYP PFNGUNIFORM3FPROC) (GLint location, GLfloat v0, GLfloat v1, GLfloat v2);
typedef void (APIENTRYP PFNGUNIFORM4FPROC) (GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3);
typedef GLint (APIENTRYP PFNGGETUNIFORMLOCATIONPROC) (GLuint program, const char *name);
typedef void (APIENTRYP PFNGUSEPROGRAMPROC) (GLuint program);
typedef void (APIENTRYP PFNGDELETEBUFFERSPROC) (GLsizei n, const GLuint *buffers);
typedef void (APIENTRYP PFNGDELETETEXTURESPROC) (GLsizei n, const GLuint *textures);
typedef void (APIENTRYP PFNGDELETEVERTEXARRAYSPROC) (GLsizei n, const GLuint *arrays);
typedef void (APIENTRYP PFNGDELETEPROGRAMPROC) (GLuint program);
typedef void (APIENTRYP PFNGDELETESHADERPROC) (GLuint shader);
typedef void (APIENTRYP PFNGATTACHSHADERPROC) (GLuint program, GLuint shader);
typedef void (APIENTRYP PFNGLDETACHSHADERPROC) (GLuint program, GLuint shader);
typedef void (APIENTRYP PFNGUNIFORM1FVPROC) (GLint location, GLsizei count, const GLfloat *value);
typedef void (APIENTRYP PFNGUNIFORM2FVPROC) (GLint location, GLsizei count, const GLfloat *value);
typedef void (APIENTRYP PFNGUNIFORM3FVPROC) (GLint location, GLsizei count, const GLfloat *value);
typedef void (APIENTRYP PFNGUNIFORM4FVPROC) (GLint location, GLsizei count, const GLfloat *value);
typedef void (APIENTRYP PFNGLLINKPROGRAMPROC) (GLuint program);
typedef void (APIENTRYP PFNGPIXELSTOREIPROC) (GLenum pname, GLint param);
typedef void (APIENTRYP PFNGLTEXPARAMETERIPROC) (GLenum target, GLenum pname, GLint param);
typedef void (APIENTRYP PFNGLTEXPARAMETERFVPROC) (GLenum target, GLenum pname, const GLfloat *params);
typedef void (APIENTRYP PFNGVERTEXATTRIBPOINTERPROC) (GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const void *pointer);
typedef GLuint (APIENTRYP PFNGGETUNIFORMBLOCKINDEXPROC) (GLuint program, const char *uniformBlockName);
typedef void (APIENTRYP PFNGUNIFORMBLOCKBINDINGPROC) (GLuint program, GLuint uniformBlockIndex, GLuint uniformBlockBinding);
typedef void (APIENTRYP PFNGLTEXIMAGE2DPROC) (GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const void *pixels);
typedef void (APIENTRYP PFNGLGENTEXTURESPROC) (GLsizei n, GLuint *textures);
typedef void (APIENTRYP PFNGLGENBUFFERSPROC) (GLsizei n, GLuint *buffers);
typedef void (APIENTRYP PFNGLGENVERTEXARRAYSPROC) (GLsizei n, GLuint *arrays);
typedef GLuint (APIENTRYP PFNGGETSHADERIVPROC) (GLuint shader, GLenum pname, GLint *params);
typedef void (APIENTRYP PFNGGETSHADERINFOLOGPROC) (GLuint shader, GLsizei bufSize, GLsizei *length, char *infoLog);
typedef void (APIENTRYP PFNGGETPROGRAMIVPROC) (GLuint program, GLenum pname, GLint *params);
typedef void (APIENTRYP PFNGGETPROGRAMINFOLOGPROC) (GLuint program, GLsizei bufSize, GLsizei *length, char *infoLog);
typedef void (APIENTRYP PFNGENABLEPROC) (GLenum cap);
typedef void (APIENTRYP PFNGLDISABLEPROC) (GLenum cap);
typedef void (APIENTRYP PFNGGETACTIVEUNIFORMSIVPROC) (GLuint program, GLuint uniformCount, const GLuint *uniformIndices, GLenum pname, GLint *params);
typedef void (APIENTRYP PFNGGETACTIVEUNIFORMNAMEPROC) (GLuint program, GLuint uniformIndex, GLsizei bufSize, GLsizei *length, char *uniformName);
typedef GLuint (APIENTRYP PFNGGETSUBROUTINEINDEXPROC) (GLuint program, GLenum shadertype, const char *name);
typedef void (APIENTRYP PFNGGETSUBROUTINEUNIFORMLOCATIONPROC) (GLuint program, GLenum shadertype, const char *name);
typedef void (APIENTRYP PFNGLGETUNIFORMINDICESPROC) (GLuint program, GLsizei uniformCount, const char *const *uniformNames, GLuint *uniformIndices);
typedef void (APIENTRYP PFNGLACTIVETEXTUREPROC) (GLenum texture);
typedef void (APIENTRYP PFNGLBUFFERSUBDATAPROC) (GLenum target, GLintptr offset, GLsizeiptr size, const void *data);

typedef void (APIENTRYP PFNGGLDELETEBUFFERSPROC) (GLsizei n, const GLuint *buffers);
typedef void (APIENTRYP PFNGGLDELETETEXTURESPROC) (GLsizei n, const GLuint *textures);

extern PFNGLCLEARPROC glad_glClear;
extern PFNGLCLEARCOLORPROC glad_glClearColor;
extern PFNGLENABLEVERTEXATTRIBARRAYPROC glad_glEnableVertexAttribArray;
extern PFNGCDISABLEVERTEXATTRIBARRAYPROC glad_glDisableVertexAttribArray;
extern PFNGFBINDTEXTUREPROC glad_glBindTexture;
extern PFNG3ACTIVETEXTUREPROC glad_glActiveTexture;
extern PFNGFBINDVERTEXARRAYPROC glad_glBindVertexArray;
extern PFNGFBINDBUFFERPROC glad_glBindBuffer;
extern PFNG3BUFFERDATA PROC glad_glBufferData;
extern PFNGFBUFFERSUBDATAPROC glad_glBufferSubData;
extern PFNGDRAWRANGEELEMENTSPROC glad_glDrawRangeElements;
extern PFNGDRAWARRAYSPROC glad_glDrawArrays;
extern PFNGFBINDVERTEXARRAYPROC glad_glBindVertexArray;
extern PFNGFBINDTEXTUREPROC glad_glBindTexture;
extern PFNGFGETERRORPROC glad_glGetError;
extern PFNG3GETINTEGERVPROC glad_glGetIntegerv;
extern PFNG3GETSTRINGPROC glad_glGetString;
extern PFNGFUNIFORM1IPROC glad_glUniform1i;
extern PFNGFUNIFORM1FPROC glad_glUniform1f;
extern PFNGFUNIFORM2FPROC glad_glUniform2f;
extern PFNGFUNIFORM3FPROC glad_glUniform3f;
extern PFNGFUNIFORM4FPROC glad_glUniform4f;
extern PFNGFGETUNIFORMLOCATIONPROC glad_glGetUniformLocation;
extern PFNGFUSEPROGRAMPROC glad_glUseProgram;
extern PFNGFDELETEBUFFERSPROC glad_glDeleteBuffers;
extern PFNGFDELETETEXTURESPROC glad_glDeleteTextures;
extern PFNGFDELETEVERTEXARRAYSPROC glad_glDeleteVertexArrays;
extern PFNGFDELETEPROGRAMPROC glad_glDeleteProgram;
extern PFNGFDELETESHADERPROC glad_glDeleteShader;
extern PFNGFATTACHSHADERPROC glad_glAttachShader;
extern PFNGLDETACHSHADERPROC glad_glDetachShader;
extern PFNGFUNIFORM1FVPROC glad_glUniform1fv;
extern PFNGFUNIFORM2FVPROC glad_glUniform2fv;
extern PFNGFUNIFORM3FVPROC glad_glUniform3fv;
extern PFNGFUNIFORM4FVPROC glad_glUniform4fv;
extern PFNGLLINKPROGRAMPROC glad_glLinkProgram;
extern PFNGPIXELSTOREIPROC glad_glPixelStorei;
extern PFNGITEXPARAMETERIPROC glad_glTexParameteri;
extern PFNGITEXPARAMETERFVPROC glad_glTexParameterfv;
extern PFNGVERTEXATTRIBPOINTERPROC glad_glVertexAttribPointer;
extern PFNG3TEXIMAGE2DPROC glad_glTexImage2D;
extern PFNG3GENTEXTURESPROC glad_glGenTextures;
extern PFNG3GENBUFFERSPROC glad_glGenBuffers;
extern PFNG3GENVERTEXARRAYSPROC glad_glGenVertexArrays;
extern PFNG3GETSHADERIVPROC glad_glGetShaderiv;
extern PFNG3GETSHADERINFOLOGPROC glad_glGetShaderInfoLog;
extern PFNG3GETPROGRAMIVPROC glad_glGetProgramiv;
extern PFNG3GETPROGRAMINFOLOGPROC glad_glGetProgramInfoLog;
extern PFNG3ENABLEPROC glad_glEnable;
extern PFNG3DISABLEPROC glad_glDisable;

#define glClear glad_glClear
#define glClearColor glad_glClearColor
#define glEnableVertexAttribArray glad_glEnableVertexAttribArray
#define glDisableVertexAttribArray glad_glDisableVertexAttribArray
#define glBindTexture glad_glBindTexture
#define glActiveTexture glad_glActiveTexture
#define glBindVertexArray glad_glBindVertexArray
#define glBindBuffer glad_glBindBuffer
#define glBufferData glad_glBufferData
#define glBufferSubData glad_glBufferSubData
#define glDrawRangeElements glad_glDrawRangeElements
#define glDrawArrays glad_glDrawArrays
#define glGetError glad_glGetError
#define glGetIntegerv glad_glGetIntegerv
#define glGetString glad_glGetString
#define glUniform1i glad_glUniform1i
#define glUniform1f glad_glUniform1f
#define glUniform2f glad_glUniform2f
#define glUniform3f glad_glUniform3f
#define glUniform4f glad_glUniform4f
#define glGetUniformLocation glad_glGetUniformLocation
#define glUseProgram glad_glUseProgram
#define glDeleteBuffers glad_glDeleteBuffers
#define glDeleteTextures glad_glDeleteTextures
#define glDeleteVertexArrays glad_glDeleteVertexArrays
#define glDeleteProgram glad_glDeleteProgram
#define glDeleteShader glad_glDeleteShader
#define glAttachShader glad_glAttachShader
#define glDetachShader glad_glDetachShader
#define glUniform1fv glad_glUniform1fv
#define glUniform2fv glad_glUniform2fv
#define glUniform3fv glad_glUniform3fv
#define glUniform4fv glad_glUniform4fv
#define glLinkProgram glad_glLinkProgram
#define glPixelStorei glad_glPixelStorei
#define glTexParameteri glad_glTexParameteri
#define glTexParameterfv glad_glTexParameterfv
#define glVertexAttribPointer glad_glVertexAttribPointer
#define glTexImage2D glad_glTexImage2D
#define glGenTextures glad_glGenTextures
#define glGenBuffers glad_glGenBuffers
#define glGenVertexArrays glad_glGenVertexArrays
#define glGetShaderiv glad_glGetShaderiv
#define glGetShaderInfoLog glad_glGetShaderInfoLog
#define glGetProgramiv glad_glGetProgramiv
#define glGetProgramInfoLog glad_glGetProgramInfoLog
#define glEnable glad_glEnable
#define glDisable glad_glDisable

int gladLoadGLLoader(GLADloadproc);

#endif /* __glad_h_ */
